[package]
name = "noti"
authors = [ "noti-rs" ]
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.27"
clap = "4.5.7"
derive_more = "0.99.18"
image = "0.25.1"
regex = "1.10.5"
serde = "1.0.203"
smithay-client-toolkit = "0.19.1"
tokio = { version = "1.38.0", features = ["full"] }
zbus = "4.3.0"
