[package]
name = "noti"
authors = [ "noti-rs" ]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.7"
image = "0.25.1"
serde = "1.0.203"
tokio = { version = "1.38.0", features = ["full"] }
zbus = "4.3.0"
