# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

max_width = 100
reorder_imports = true
edition = "2021"
fn_params_layout = "Tall"
fn_call_width = 60
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
merge_derives = true
newline_style = "Unix"
single_line_let_else_max_width = 0
tab_spaces = 4
use_field_init_shorthand = true
