[package]
name = "client"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
dbus.workspace = true

anyhow.workspace = true
async-io.workspace = true
log.workspace = true
zbus.workspace = true
