[package]
name = "client"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
dbus = { path = "../dbus" }
zbus = "4.4.0"
