[package]
name = "config"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
dbus = { path = "../dbus" }
anyhow = { workspace = true }

inotify = "0.10.2"
once_cell = "1.19.0"
serde = "1.0.205"
toml = "0.8.19"
