[package]
name = "config"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
macros = { path = "../macros" }
dbus = { path = "../dbus" }
anyhow = { workspace = true }
log = { workspace = true }

inotify = "0.10.2"
serde = "1.0.205"
toml = "0.8.19"
