[package]
name = "backend"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
dbus = { workspace = true }
config = { workspace = true }
render = { workspace = true }
shared = { workspace = true }
filetype = { path = "../filetype" }

tempfile = "3.12.0"
wayland-client = "0.31.5"
wayland-protocols = { version = "0.32.3", features = ["client", "wayland-client", "staging"] }
wayland-protocols-wlr = { version = "0.3.3", features = ["client", "wayland-client"] }
indexmap = "2.4.0"
humantime = "2.1.0"
chrono = "0.4.39"
