[package]
name = "backend"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
dbus = { path = "../dbus" }
config = { path = "../config" }

ab_glyph = "0.2.28"
derive_builder = "0.20.0"
image = "0.25.2"
itertools = "0.13.0"
owned_ttf_parser = "0.24.0"
rayon = "1.10.0"
resvg = "0.43.0"
tempfile = "3.12.0"
wayland-client = "0.31.5"
wayland-protocols = { version = "0.32.3", features = ["client", "wayland-client"] }
wayland-protocols-wlr = { version = "0.3.3", features = ["client", "wayland-client"] }
derive_more = { version = "1.0.0", features = ["display"] }
