name: "Checks"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  nix-checks:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        check_name: ["noti-clippy", "noti-test", "noti-fmt", "build"]

    steps:
      - uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""

      - name: Run ${{ matrix.check_name }}
        run: nix build .#checks.x86_64-linux.${{ matrix.check_name }}
